apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  ports:
    - port: 8090
      name: http
  type: ClusterIP
  selector:
    app: {{ include "ibus-adapter-stream-helm.name" . }}
