apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ibus-adapter-stream-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          {{- $replicas := int (toString .Values.replicaCount) }}
          {{- $appName := include "ibus-adapter-stream-helm.name" . }}
          {{- $serviceName := (toString .Values.serviceName) }}
          {{- range $i := until $replicas }}
          - path: /{{$appName}}-{{$i}}(/|$)(.*)
            backend:
              serviceName: {{$serviceName }}-{{$i}}
              servicePort: 8090
          {{- end }}