apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cerner-bdd-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cerner-bdd-agent.name" . }}
    helm.sh/chart: {{ include "cerner-bdd-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cerner-bdd-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cerner-bdd-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
{{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.type }}
{{- end }}
          env:
{{ toYaml .Values.pod.env | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}