apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cerner-bdd-agent-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /agent(/|$)(.*)
            backend:
              serviceName: cerner-bdd-agent-service
              servicePort: 8095