apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "cerner-bdd-agent.name" . }}
    helm.sh/chart: {{ include "cerner-bdd-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.type }}
      name: {{ $port.name }}
      nodePort: {{ $port.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cerner-bdd-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}