apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ibus-adapter-rest-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /rest(/|$)(.*)
            backend:
              serviceName: ibus-adapter-rest-service
              servicePort: 8080
          - path: /retrospective(/|$)(.*)
            backend:
              serviceName: ibus-adapter-retrospective-service
              servicePort: 8080
